# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table `DIFFICULTY_LEVEL` (`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`NAME` VARCHAR(254) NOT NULL,`POINTS` INTEGER NOT NULL,`DESCRIPTION` VARCHAR(254));
create table `DOMAINS` (`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`NAME` VARCHAR(254) NOT NULL,`DESCRIPTION` VARCHAR(254));
create table `INTERVIEW_QUESTION` (`SESSION_ID` BIGINT NOT NULL,`QUESTION_ID` BIGINT NOT NULL,`RESPONSE_SATISFACTION_ID` BIGINT NOT NULL,`COMMENT` VARCHAR(254) NOT NULL);
alter table `INTERVIEW_QUESTION` add constraint `iq_pk` primary key(`SESSION_ID`,`QUESTION_ID`);
create table `INTERVIEW_SESSION` (`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`SESSION_DATE` DATE NOT NULL,`INTERVIEWER` VARCHAR(254) NOT NULL,`INTERVIEWEE` VARCHAR(254) NOT NULL,`COMMENTS` VARCHAR(254) NOT NULL);
create table `LANGUAGES` (`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`LANGUAGE` VARCHAR(254) NOT NULL);
create table `QUESTIONS` (`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`Q` VARCHAR(254) NOT NULL,`A` VARCHAR(254) NOT NULL,`LANGUAGE_ID` BIGINT NOT NULL,`DIFFICULTY_LEVEL_ID` BIGINT NOT NULL,`COMMENT` VARCHAR(254),`TIMES_ASKED` INTEGER NOT NULL,`LAST_ASKED` DATE);
create table `RESPONSE_SATISFACTION_LEVEL` (`ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`SATISFACTION_LEVEL` VARCHAR(254) NOT NULL,`POINTS` INTEGER NOT NULL,`COMMENT` VARCHAR(254));
alter table `INTERVIEW_QUESTION` add constraint `session_fk` foreign key(`SESSION_ID`) references `INTERVIEW_SESSION`(`ID`) on update NO ACTION on delete NO ACTION;
alter table `INTERVIEW_QUESTION` add constraint `question_fk` foreign key(`SESSION_ID`) references `QUESTIONS`(`ID`) on update NO ACTION on delete NO ACTION;
alter table `INTERVIEW_QUESTION` add constraint `response_fk` foreign key(`RESPONSE_SATISFACTION_ID`) references `RESPONSE_SATISFACTION_LEVEL`(`ID`) on update NO ACTION on delete NO ACTION;
alter table `QUESTIONS` add constraint `FK_DL` foreign key(`DIFFICULTY_LEVEL_ID`) references `DIFFICULTY_LEVEL`(`ID`) on update NO ACTION on delete NO ACTION;

# --- !Downs

ALTER TABLE INTERVIEW_QUESTION DROP FOREIGN KEY session_fk;
ALTER TABLE INTERVIEW_QUESTION DROP FOREIGN KEY question_fk;
ALTER TABLE INTERVIEW_QUESTION DROP FOREIGN KEY response_fk;
ALTER TABLE QUESTIONS DROP FOREIGN KEY FK_DL;
drop table `DIFFICULTY_LEVEL`;
drop table `DOMAINS`;
alter table `INTERVIEW_QUESTION` drop constraint `iq_pk`;
drop table `INTERVIEW_QUESTION`;
drop table `INTERVIEW_SESSION`;
drop table `LANGUAGES`;
drop table `QUESTIONS`;
drop table `RESPONSE_SATISFACTION_LEVEL`;

